wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705498333.837711
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      3:
      - 7
      - 23
      4: 3.10.13
      5: 0.16.2
      6: 4.31.0
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: current_step
      6:
      - 3
    - 1: epoch
      5: 1
      6:
      - 1
      - 3
    - 1: train/loss
      5: 1
      6:
      - 1
      - 3
    - 1: train/learning_rate
      5: 1
      6:
      - 1
      - 3
    - 1: validate/score
      5: 1
      6:
      - 1
      - 3
    - 1: validate/segment_score
      5: 1
      6:
      - 1
      - 3
    - 1: validate/frame_score
      5: 1
      6:
      - 1
      - 3
